spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 8799
    url: jdbc:mysql://localhost:3306/thruth?characterEncoding=utf-8&useSSL=false
  jap:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379


server:
  servlet:
    context-path: /truthMan
mybatis:
  mapper-locations: Classpath:mapper/*.xml