spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 8799
    url: jdbc:mysql://localhost:3306/thruth?characterEncoding=utf-8&useSSL=false
  jap:
    show-sql: true

server:
  servlet:
    context-path: /truth